name: roo
version: '1.3.8'
summary: The Roo programming language
description: |
  Roo is a cross-platform dynamically-typed object-orientated interpreted open source scripting language which takes inspiration from Ruby (everything is an object) and Python (indentation matters for block scoping).

grade: stable
confinement: strict

parts:
  roo:
    source: https://github.com/roolang/roo/files/1763631/roo-138-linux64.zip
    plugin: dump

apps:
  roo: 
    command: roo
