name: roo
version: '2.0.2'
summary: The Roo programming language
description: |
  Roo is a cross-platform dynamically-typed object-orientated interpreted open source scripting language which takes inspiration from Ruby and Javascript.

grade: stable
confinement: strict

parts:
  roo:
    source: https://github.com/gkjpettet/roo/files/2188500/roo-202-linux.zip
    plugin: dump

apps:
  roo: 
    command: roo
